import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Todo: NextPage = () => {
  const utils = trpc.useContext();
  const todos = trpc.todo.getAll.useQuery();
  const deleteTodo = trpc.todo.delete.useMutation({
    onSettled: () => {
      utils.todo.getAll.invalidate();
    },
  });
  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>Todo</h1>
        <div>
          {todos.data?.map((todo) => (
            <div key={todo.id} className="pt-10">
              <p>{todo.title}</p>
              <button
                onClick={() => {
                  deleteTodo.mutate({ id: todo.id });
                }}
                className="bg-cyan-300"
              >
                Delete
              </button>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Todo;
